[workspace]
resolver = "3"
members = ["bindings"]

[workspace.package]
keywords = ["anoma", "evm", "protocol-adapter", "forwarder"]
authors = ["Anoma Foundation"]
license = "MIT"
repository = "https://github.com/anoma/generic-call-forwarder"
homepage = "https://anoma.net/"
edition = "2024"

[workspace.dependencies]
alloy = { version = "2.0.5", features = ["full", "eip712", "node-bindings"] }
alloy-chains = "0.2.33"
anoma-pa-evm-bindings = "2.2.0"
dotenvy = "0.15.7"
serde = { version = "1.0.228", default-features = false }
serde_json = "1.0"
thiserror = "2.0.18"
tokio = { version = "1.52", features = ["rt-multi-thread"] }

anoma-generic-call-forwarder-bindings = { path = "bindings" }
